### ISSUE TITLE
Please consider distributing via F-Droid

### ISSUE THREAD

**Issue by jeffgazso** [aicodix/rattlegram#10] opened 2023-10-05 20:05 UTC
Please consider distributing Rattlegram via [F-Droid](https://f-droid.org/) in addition to the Google App store. In case you're not familiar, F-Droid is an app store specifically for open source Android apps.

**Comment by xdsopl** [comment] 2023-10-05 21:10
Duplicate of #2

**Closed by xdsopl** 2023-10-05 21:10 UTC
