### ISSUE TITLE
AES Encryption

### ISSUE THREAD

**Issue by Thom-x** [aicodix/rattlegram#14] opened 2023-10-29 12:26 UTC
Thank you for your project, it works really well !

It would be wonderful to implement some sort of encryption, I'm mostly thinking about radio amateur transmissions.
The addition of AES encryption will ensure a high level of security for audio text transmissions, protecting data from unauthorized access and will safeguard the privacy of user conversations.

About the implementation details, it could be a randomly generated encryption key that could be shared between devices (why not with QR code as well ?).

Thank you for your time and consideration.

**Comment by xdsopl** [comment] 2023-10-29 14:31
Duplicate of #11

**Closed by xdsopl** 2023-10-29 14:31 UTC
